server:
  port: 5000
spring:
  application:
    name: api-gateway
#zuul:
#  routes:
#    hello-service:
#      path: /hello-service/**
#      serviceId: hello-service


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/,http://localhost:8889/eureka/







